name: Run Tests

on: pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Project
        uses: actions/checkout@v6
      
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod 
          cache: true

      - name: Go cache
        run: |
          go env GOCACHE
          du -sh "$(go env GOCACHE)" || true

      - name: Download dependencies
        run: time go mod download

      - name: Test
        env:
          GODEBUG: gocachetest=1
        run: time go test ./...